/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { PublicProfileButtonProps } from "./PublicProfileButton";
import { MyPurchasesButtonProps } from "./MyPurchasesButton";
import { MyFavoritesButtonProps } from "./MyFavoritesButton";
import { MySellingsButtonProps } from "./MySellingsButton";
import { FavoritePromptProps } from "./FavoritePrompt";
import { FavoritePurchasedPrompt2Props } from "./FavoritePurchasedPrompt2";
import { FavoritePurchasedPromptProps } from "./FavoritePurchasedPrompt";
import { FavoritePrompt2Props } from "./FavoritePrompt2";
import { PageselectionProps } from "./Pageselection";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MyFavoritesPageOverridesProps = {
    MyFavoritesPage?: PrimitiveOverrideProps<FlexProps>;
    "Frame 270"?: PrimitiveOverrideProps<FlexProps>;
    "Dashboard Illustration"?: PrimitiveOverrideProps<FlexProps>;
    Group52629182?: PrimitiveOverrideProps<ViewProps>;
    Group52629183?: PrimitiveOverrideProps<ViewProps>;
    Vector52629184?: PrimitiveOverrideProps<IconProps>;
    Vector52629185?: PrimitiveOverrideProps<IconProps>;
    Vector52629186?: PrimitiveOverrideProps<IconProps>;
    Group52629187?: PrimitiveOverrideProps<ViewProps>;
    Vector52629188?: PrimitiveOverrideProps<IconProps>;
    Vector52629189?: PrimitiveOverrideProps<IconProps>;
    Vector52629190?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52629191?: PrimitiveOverrideProps<ViewProps>;
    b_1_idea52629192?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52629193?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52629194?: PrimitiveOverrideProps<ViewProps>;
    Vector52629195?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52629196?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52629197?: PrimitiveOverrideProps<IconProps>;
    Group52629198?: PrimitiveOverrideProps<ViewProps>;
    Vector52629199?: PrimitiveOverrideProps<IconProps>;
    Vector52629200?: PrimitiveOverrideProps<IconProps>;
    Vector52629201?: PrimitiveOverrideProps<IconProps>;
    Group52629202?: PrimitiveOverrideProps<ViewProps>;
    Vector52629203?: PrimitiveOverrideProps<IconProps>;
    Vector52629204?: PrimitiveOverrideProps<IconProps>;
    Group52629205?: PrimitiveOverrideProps<ViewProps>;
    Vector52629206?: PrimitiveOverrideProps<IconProps>;
    Vector52629207?: PrimitiveOverrideProps<IconProps>;
    Group52629208?: PrimitiveOverrideProps<ViewProps>;
    Vector52629209?: PrimitiveOverrideProps<IconProps>;
    Vector52629210?: PrimitiveOverrideProps<IconProps>;
    Vector52629211?: PrimitiveOverrideProps<IconProps>;
    Group52629212?: PrimitiveOverrideProps<ViewProps>;
    Vector52629213?: PrimitiveOverrideProps<IconProps>;
    Vector52629214?: PrimitiveOverrideProps<IconProps>;
    Vector52629215?: PrimitiveOverrideProps<IconProps>;
    Group52629216?: PrimitiveOverrideProps<ViewProps>;
    Vector52629217?: PrimitiveOverrideProps<IconProps>;
    Vector52629218?: PrimitiveOverrideProps<IconProps>;
    Vector52629219?: PrimitiveOverrideProps<IconProps>;
    Vector52629220?: PrimitiveOverrideProps<IconProps>;
    Vector52629221?: PrimitiveOverrideProps<IconProps>;
    Vector52629222?: PrimitiveOverrideProps<IconProps>;
    Vector52629223?: PrimitiveOverrideProps<IconProps>;
    Vector52629224?: PrimitiveOverrideProps<IconProps>;
    Group52629225?: PrimitiveOverrideProps<ViewProps>;
    Vector52629226?: PrimitiveOverrideProps<IconProps>;
    Vector52629227?: PrimitiveOverrideProps<IconProps>;
    Group52629228?: PrimitiveOverrideProps<ViewProps>;
    Vector52629229?: PrimitiveOverrideProps<IconProps>;
    Vector52629230?: PrimitiveOverrideProps<IconProps>;
    Group52629231?: PrimitiveOverrideProps<ViewProps>;
    Vector52629232?: PrimitiveOverrideProps<IconProps>;
    Group52629233?: PrimitiveOverrideProps<ViewProps>;
    Vector52629234?: PrimitiveOverrideProps<IconProps>;
    Group52629235?: PrimitiveOverrideProps<ViewProps>;
    Vector52629236?: PrimitiveOverrideProps<IconProps>;
    Vector52629237?: PrimitiveOverrideProps<IconProps>;
    Vector52629238?: PrimitiveOverrideProps<IconProps>;
    Vector52629239?: PrimitiveOverrideProps<IconProps>;
    Group52629240?: PrimitiveOverrideProps<ViewProps>;
    Vector52629241?: PrimitiveOverrideProps<IconProps>;
    Vector52629242?: PrimitiveOverrideProps<IconProps>;
    Vector52629243?: PrimitiveOverrideProps<IconProps>;
    Vector52629244?: PrimitiveOverrideProps<IconProps>;
    Vector52629245?: PrimitiveOverrideProps<IconProps>;
    Vector52629246?: PrimitiveOverrideProps<IconProps>;
    Group52629247?: PrimitiveOverrideProps<ViewProps>;
    Group52629248?: PrimitiveOverrideProps<ViewProps>;
    Vector52629249?: PrimitiveOverrideProps<IconProps>;
    Vector52629250?: PrimitiveOverrideProps<IconProps>;
    Group52629251?: PrimitiveOverrideProps<ViewProps>;
    Vector52629252?: PrimitiveOverrideProps<IconProps>;
    Vector52629253?: PrimitiveOverrideProps<IconProps>;
    Group52629254?: PrimitiveOverrideProps<ViewProps>;
    Vector52629255?: PrimitiveOverrideProps<IconProps>;
    Vector52629256?: PrimitiveOverrideProps<IconProps>;
    Group52629257?: PrimitiveOverrideProps<ViewProps>;
    Vector52629258?: PrimitiveOverrideProps<IconProps>;
    Vector52629259?: PrimitiveOverrideProps<IconProps>;
    Dashboard?: PrimitiveOverrideProps<TextProps>;
    "Frame 242"?: PrimitiveOverrideProps<FlexProps>;
    "Public Profile Button"?: PublicProfileButtonProps;
    "My Purchases Button"?: MyPurchasesButtonProps;
    "My Favorites Button"?: MyFavoritesButtonProps;
    "My Sellings Button"?: MySellingsButtonProps;
    "Frame 241"?: PrimitiveOverrideProps<FlexProps>;
    "Headings with Lines"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 133"?: PrimitiveOverrideProps<FlexProps>;
    "My Favorites"?: PrimitiveOverrideProps<TextProps>;
    "(16 items)"?: PrimitiveOverrideProps<TextProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Frame 84"?: PrimitiveOverrideProps<FlexProps>;
    "Vertical Prompt List"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 78"?: PrimitiveOverrideProps<FlexProps>;
    "Favorite Prompt49221837"?: FavoritePromptProps;
    "Favorite Purchased Prompt 2"?: FavoritePurchasedPrompt2Props;
    "Favorite Prompt49221839"?: FavoritePromptProps;
    "Frame 79"?: PrimitiveOverrideProps<FlexProps>;
    "Favorite Purchased Prompt49221841"?: FavoritePurchasedPromptProps;
    "Favorite Purchased Prompt 3"?: FavoritePurchasedPrompt2Props;
    "Favorite Prompt 3"?: FavoritePrompt2Props;
    "Frame 80"?: PrimitiveOverrideProps<FlexProps>;
    "Favorite Prompt49221845"?: FavoritePromptProps;
    "Favorite Prompt 2"?: FavoritePrompt2Props;
    "Favorite Purchased Prompt49221847"?: FavoritePurchasedPromptProps;
    "page selection"?: PageselectionProps;
} & EscapeHatchProps;
export declare type MyFavoritesPageProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: MyFavoritesPageOverridesProps | undefined | null;
}>;
export default function MyFavoritesPage(props: MyFavoritesPageProps): React.ReactElement;
