/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { PublicProfileButtonProps } from "./PublicProfileButton";
import { MyPurchasesButtonProps } from "./MyPurchasesButton";
import { MyFavoritesButtonProps } from "./MyFavoritesButton";
import { MySellingsButtonProps } from "./MySellingsButton";
import { PurchasedpromptThumbnailsmallProps } from "./PurchasedpromptThumbnailsmall";
import { PurchasedPromptThumbnailsmall2Props } from "./PurchasedPromptThumbnailsmall2";
import { PageselectionProps } from "./Pageselection";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MyPurchasesPageOverridesProps = {
    MyPurchasesPage?: PrimitiveOverrideProps<FlexProps>;
    "Frame 270"?: PrimitiveOverrideProps<FlexProps>;
    "Dashboard Illustration"?: PrimitiveOverrideProps<FlexProps>;
    Group52627292?: PrimitiveOverrideProps<ViewProps>;
    Group52627293?: PrimitiveOverrideProps<ViewProps>;
    Vector52627294?: PrimitiveOverrideProps<IconProps>;
    Vector52627295?: PrimitiveOverrideProps<IconProps>;
    Vector52627296?: PrimitiveOverrideProps<IconProps>;
    Group52627297?: PrimitiveOverrideProps<ViewProps>;
    Vector52627298?: PrimitiveOverrideProps<IconProps>;
    Vector52627299?: PrimitiveOverrideProps<IconProps>;
    Vector52627300?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52627301?: PrimitiveOverrideProps<ViewProps>;
    b_1_idea52627302?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52627303?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52627304?: PrimitiveOverrideProps<ViewProps>;
    Vector52627305?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52627306?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52627307?: PrimitiveOverrideProps<IconProps>;
    Group52627308?: PrimitiveOverrideProps<ViewProps>;
    Vector52627309?: PrimitiveOverrideProps<IconProps>;
    Vector52627310?: PrimitiveOverrideProps<IconProps>;
    Vector52627311?: PrimitiveOverrideProps<IconProps>;
    Group52627312?: PrimitiveOverrideProps<ViewProps>;
    Vector52627313?: PrimitiveOverrideProps<IconProps>;
    Vector52627314?: PrimitiveOverrideProps<IconProps>;
    Group52627315?: PrimitiveOverrideProps<ViewProps>;
    Vector52627316?: PrimitiveOverrideProps<IconProps>;
    Vector52627317?: PrimitiveOverrideProps<IconProps>;
    Group52627318?: PrimitiveOverrideProps<ViewProps>;
    Vector52627319?: PrimitiveOverrideProps<IconProps>;
    Vector52627320?: PrimitiveOverrideProps<IconProps>;
    Vector52627321?: PrimitiveOverrideProps<IconProps>;
    Group52627322?: PrimitiveOverrideProps<ViewProps>;
    Vector52627323?: PrimitiveOverrideProps<IconProps>;
    Vector52627324?: PrimitiveOverrideProps<IconProps>;
    Vector52627325?: PrimitiveOverrideProps<IconProps>;
    Group52627326?: PrimitiveOverrideProps<ViewProps>;
    Vector52627327?: PrimitiveOverrideProps<IconProps>;
    Vector52627328?: PrimitiveOverrideProps<IconProps>;
    Vector52627329?: PrimitiveOverrideProps<IconProps>;
    Vector52627330?: PrimitiveOverrideProps<IconProps>;
    Vector52627331?: PrimitiveOverrideProps<IconProps>;
    Vector52627332?: PrimitiveOverrideProps<IconProps>;
    Vector52627333?: PrimitiveOverrideProps<IconProps>;
    Vector52627334?: PrimitiveOverrideProps<IconProps>;
    Group52627335?: PrimitiveOverrideProps<ViewProps>;
    Vector52627336?: PrimitiveOverrideProps<IconProps>;
    Vector52627337?: PrimitiveOverrideProps<IconProps>;
    Group52627338?: PrimitiveOverrideProps<ViewProps>;
    Vector52627339?: PrimitiveOverrideProps<IconProps>;
    Vector52627340?: PrimitiveOverrideProps<IconProps>;
    Group52627341?: PrimitiveOverrideProps<ViewProps>;
    Vector52627342?: PrimitiveOverrideProps<IconProps>;
    Group52627343?: PrimitiveOverrideProps<ViewProps>;
    Vector52627344?: PrimitiveOverrideProps<IconProps>;
    Group52627345?: PrimitiveOverrideProps<ViewProps>;
    Vector52627346?: PrimitiveOverrideProps<IconProps>;
    Vector52627347?: PrimitiveOverrideProps<IconProps>;
    Vector52627348?: PrimitiveOverrideProps<IconProps>;
    Vector52627349?: PrimitiveOverrideProps<IconProps>;
    Group52627350?: PrimitiveOverrideProps<ViewProps>;
    Vector52627351?: PrimitiveOverrideProps<IconProps>;
    Vector52627352?: PrimitiveOverrideProps<IconProps>;
    Vector52627353?: PrimitiveOverrideProps<IconProps>;
    Vector52627354?: PrimitiveOverrideProps<IconProps>;
    Vector52627355?: PrimitiveOverrideProps<IconProps>;
    Vector52627356?: PrimitiveOverrideProps<IconProps>;
    Group52627357?: PrimitiveOverrideProps<ViewProps>;
    Group52627358?: PrimitiveOverrideProps<ViewProps>;
    Vector52627359?: PrimitiveOverrideProps<IconProps>;
    Vector52627360?: PrimitiveOverrideProps<IconProps>;
    Group52627361?: PrimitiveOverrideProps<ViewProps>;
    Vector52627362?: PrimitiveOverrideProps<IconProps>;
    Vector52627363?: PrimitiveOverrideProps<IconProps>;
    Group52627364?: PrimitiveOverrideProps<ViewProps>;
    Vector52627365?: PrimitiveOverrideProps<IconProps>;
    Vector52627366?: PrimitiveOverrideProps<IconProps>;
    Group52627367?: PrimitiveOverrideProps<ViewProps>;
    Vector52627368?: PrimitiveOverrideProps<IconProps>;
    Vector52627369?: PrimitiveOverrideProps<IconProps>;
    Dashboard?: PrimitiveOverrideProps<TextProps>;
    "Frame 242"?: PrimitiveOverrideProps<FlexProps>;
    "Public Profile Button"?: PublicProfileButtonProps;
    "My Purchases Button"?: MyPurchasesButtonProps;
    "My Favorites Button"?: MyFavoritesButtonProps;
    "My Sellings Button"?: MySellingsButtonProps;
    "Frame 241"?: PrimitiveOverrideProps<FlexProps>;
    "Headings with Lines"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 133"?: PrimitiveOverrideProps<FlexProps>;
    "My Purchases"?: PrimitiveOverrideProps<TextProps>;
    "(12 items)"?: PrimitiveOverrideProps<TextProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Frame 84"?: PrimitiveOverrideProps<FlexProps>;
    "Vertical Prompt List"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 78"?: PrimitiveOverrideProps<FlexProps>;
    "Purchased prompt Thumbnail (small)49221155"?: PurchasedpromptThumbnailsmallProps;
    "Purchased Prompt Thumbnail (small) 249221156"?: PurchasedPromptThumbnailsmall2Props;
    "Purchased prompt Thumbnail (small)49221157"?: PurchasedpromptThumbnailsmallProps;
    "Frame 79"?: PrimitiveOverrideProps<FlexProps>;
    "Purchased prompt Thumbnail (small)49221159"?: PurchasedpromptThumbnailsmallProps;
    "Purchased Prompt Thumbnail (small) 249221160"?: PurchasedPromptThumbnailsmall2Props;
    "Purchased Prompt Thumbnail (small) 3"?: PurchasedPromptThumbnailsmall2Props;
    "Frame 80"?: PrimitiveOverrideProps<FlexProps>;
    "Purchased prompt Thumbnail (small)49221163"?: PurchasedpromptThumbnailsmallProps;
    "Purchased Prompt Thumbnail (small) 249221164"?: PurchasedPromptThumbnailsmall2Props;
    "Purchased prompt Thumbnail (small)49221165"?: PurchasedpromptThumbnailsmallProps;
    "page selection"?: PageselectionProps;
} & EscapeHatchProps;
export declare type MyPurchasesPageProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: MyPurchasesPageOverridesProps | undefined | null;
}>;
export default function MyPurchasesPage(props: MyPurchasesPageProps): React.ReactElement;
