/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { PublicProfileButtonProps } from "./PublicProfileButton";
import { MyPurchasesButtonProps } from "./MyPurchasesButton";
import { MyFavoritesButtonProps } from "./MyFavoritesButton";
import { MySellingsButtonProps } from "./MySellingsButton";
import { SortSellingDropdownProps } from "./SortSellingDropdown";
import { ForSaleSellingPromptProps } from "./ForSaleSellingPrompt";
import { PendingSellingPromptProps } from "./PendingSellingPrompt";
import { DeniedSellingPromptProps } from "./DeniedSellingPrompt";
import { ReadyforSaleSellingPromptProps } from "./ReadyforSaleSellingPrompt";
import { PageselectionProps } from "./Pageselection";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MySellingPageOverridesProps = {
    MySellingPage?: PrimitiveOverrideProps<FlexProps>;
    "Frame 270"?: PrimitiveOverrideProps<FlexProps>;
    "Dashboard Illustration"?: PrimitiveOverrideProps<FlexProps>;
    Group52630883?: PrimitiveOverrideProps<ViewProps>;
    Group52630884?: PrimitiveOverrideProps<ViewProps>;
    Vector52630885?: PrimitiveOverrideProps<IconProps>;
    Vector52630886?: PrimitiveOverrideProps<IconProps>;
    Vector52630887?: PrimitiveOverrideProps<IconProps>;
    Group52630888?: PrimitiveOverrideProps<ViewProps>;
    Vector52630889?: PrimitiveOverrideProps<IconProps>;
    Vector52630890?: PrimitiveOverrideProps<IconProps>;
    Vector52630891?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52630892?: PrimitiveOverrideProps<ViewProps>;
    b_1_idea52630893?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52630894?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52630895?: PrimitiveOverrideProps<ViewProps>;
    Vector52630896?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52630897?: PrimitiveOverrideProps<IconProps>;
    b_1_idea52630898?: PrimitiveOverrideProps<IconProps>;
    Group52630899?: PrimitiveOverrideProps<ViewProps>;
    Vector52630900?: PrimitiveOverrideProps<IconProps>;
    Vector52630901?: PrimitiveOverrideProps<IconProps>;
    Vector52630902?: PrimitiveOverrideProps<IconProps>;
    Group52630903?: PrimitiveOverrideProps<ViewProps>;
    Vector52630904?: PrimitiveOverrideProps<IconProps>;
    Vector52630905?: PrimitiveOverrideProps<IconProps>;
    Group52630906?: PrimitiveOverrideProps<ViewProps>;
    Vector52630907?: PrimitiveOverrideProps<IconProps>;
    Vector52630908?: PrimitiveOverrideProps<IconProps>;
    Group52630909?: PrimitiveOverrideProps<ViewProps>;
    Vector52630910?: PrimitiveOverrideProps<IconProps>;
    Vector52630911?: PrimitiveOverrideProps<IconProps>;
    Vector52630912?: PrimitiveOverrideProps<IconProps>;
    Group52630913?: PrimitiveOverrideProps<ViewProps>;
    Vector52630914?: PrimitiveOverrideProps<IconProps>;
    Vector52630915?: PrimitiveOverrideProps<IconProps>;
    Vector52630916?: PrimitiveOverrideProps<IconProps>;
    Group52630917?: PrimitiveOverrideProps<ViewProps>;
    Vector52630918?: PrimitiveOverrideProps<IconProps>;
    Vector52630919?: PrimitiveOverrideProps<IconProps>;
    Vector52630920?: PrimitiveOverrideProps<IconProps>;
    Vector52630921?: PrimitiveOverrideProps<IconProps>;
    Vector52630922?: PrimitiveOverrideProps<IconProps>;
    Vector52630923?: PrimitiveOverrideProps<IconProps>;
    Vector52630924?: PrimitiveOverrideProps<IconProps>;
    Vector52630925?: PrimitiveOverrideProps<IconProps>;
    Group52630926?: PrimitiveOverrideProps<ViewProps>;
    Vector52630927?: PrimitiveOverrideProps<IconProps>;
    Vector52630928?: PrimitiveOverrideProps<IconProps>;
    Group52630929?: PrimitiveOverrideProps<ViewProps>;
    Vector52630930?: PrimitiveOverrideProps<IconProps>;
    Vector52630931?: PrimitiveOverrideProps<IconProps>;
    Group52630932?: PrimitiveOverrideProps<ViewProps>;
    Vector52630933?: PrimitiveOverrideProps<IconProps>;
    Group52630934?: PrimitiveOverrideProps<ViewProps>;
    Vector52630935?: PrimitiveOverrideProps<IconProps>;
    Group52630936?: PrimitiveOverrideProps<ViewProps>;
    Vector52630937?: PrimitiveOverrideProps<IconProps>;
    Vector52630938?: PrimitiveOverrideProps<IconProps>;
    Vector52630939?: PrimitiveOverrideProps<IconProps>;
    Vector52630940?: PrimitiveOverrideProps<IconProps>;
    Group52630941?: PrimitiveOverrideProps<ViewProps>;
    Vector52630942?: PrimitiveOverrideProps<IconProps>;
    Vector52630943?: PrimitiveOverrideProps<IconProps>;
    Vector52630944?: PrimitiveOverrideProps<IconProps>;
    Vector52630945?: PrimitiveOverrideProps<IconProps>;
    Vector52630946?: PrimitiveOverrideProps<IconProps>;
    Vector52630947?: PrimitiveOverrideProps<IconProps>;
    Group52630948?: PrimitiveOverrideProps<ViewProps>;
    Group52630949?: PrimitiveOverrideProps<ViewProps>;
    Vector52630950?: PrimitiveOverrideProps<IconProps>;
    Vector52630951?: PrimitiveOverrideProps<IconProps>;
    Group52630952?: PrimitiveOverrideProps<ViewProps>;
    Vector52630953?: PrimitiveOverrideProps<IconProps>;
    Vector52630954?: PrimitiveOverrideProps<IconProps>;
    Group52630955?: PrimitiveOverrideProps<ViewProps>;
    Vector52630956?: PrimitiveOverrideProps<IconProps>;
    Vector52630957?: PrimitiveOverrideProps<IconProps>;
    Group52630958?: PrimitiveOverrideProps<ViewProps>;
    Vector52630959?: PrimitiveOverrideProps<IconProps>;
    Vector52630960?: PrimitiveOverrideProps<IconProps>;
    Dashboard?: PrimitiveOverrideProps<TextProps>;
    "Frame 243"?: PrimitiveOverrideProps<FlexProps>;
    "Public Profile Button"?: PublicProfileButtonProps;
    "My Purchases Button"?: MyPurchasesButtonProps;
    "My Favorites Button"?: MyFavoritesButtonProps;
    "My Sellings Button"?: MySellingsButtonProps;
    "Frame 241"?: PrimitiveOverrideProps<FlexProps>;
    "Headings with Lines"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 133"?: PrimitiveOverrideProps<FlexProps>;
    "My Selling"?: PrimitiveOverrideProps<TextProps>;
    "(16 items)"?: PrimitiveOverrideProps<TextProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Frame 266"?: PrimitiveOverrideProps<FlexProps>;
    "Sort Selling Dropdown"?: SortSellingDropdownProps;
    "Frame 84"?: PrimitiveOverrideProps<FlexProps>;
    "Vertical Prompt List"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 78"?: PrimitiveOverrideProps<FlexProps>;
    "For Sale Selling Prompt50627947"?: ForSaleSellingPromptProps;
    "Pending Selling Prompt50627948"?: PendingSellingPromptProps;
    "For Sale Selling Prompt50627949"?: ForSaleSellingPromptProps;
    "Frame 79"?: PrimitiveOverrideProps<FlexProps>;
    "Denied Selling Prompt50627951"?: DeniedSellingPromptProps;
    "Favorite Purchased Prompt 3"?: ReadyforSaleSellingPromptProps;
    "Pending Selling Prompt50627953"?: PendingSellingPromptProps;
    "Frame 80"?: PrimitiveOverrideProps<FlexProps>;
    "For Sale Selling Prompt50627955"?: ForSaleSellingPromptProps;
    "Pending Selling Prompt50627956"?: PendingSellingPromptProps;
    "Denied Selling Prompt50627957"?: DeniedSellingPromptProps;
    "page selection"?: PageselectionProps;
} & EscapeHatchProps;
export declare type MySellingPageProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: MySellingPageOverridesProps | undefined | null;
}>;
export default function MySellingPage(props: MySellingPageProps): React.ReactElement;
