/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { UpdateButtonProps } from "./UpdateButton";
import { DeleteAccountButtonProps } from "./DeleteAccountButton";
import { CheckBoxbuttonProps } from "./CheckBoxbutton";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SettingsPageOverridesProps = {
    SettingsPage?: PrimitiveOverrideProps<FlexProps>;
    "Frame 270"?: PrimitiveOverrideProps<FlexProps>;
    "Dashboard Illustration"?: PrimitiveOverrideProps<FlexProps>;
    Group53628624?: PrimitiveOverrideProps<ViewProps>;
    Group53628625?: PrimitiveOverrideProps<ViewProps>;
    Vector53628626?: PrimitiveOverrideProps<IconProps>;
    Vector53628627?: PrimitiveOverrideProps<IconProps>;
    Group53628628?: PrimitiveOverrideProps<ViewProps>;
    Vector53628629?: PrimitiveOverrideProps<IconProps>;
    Vector53628630?: PrimitiveOverrideProps<IconProps>;
    Group53628631?: PrimitiveOverrideProps<ViewProps>;
    Vector53628632?: PrimitiveOverrideProps<IconProps>;
    Vector53628633?: PrimitiveOverrideProps<IconProps>;
    Group53628634?: PrimitiveOverrideProps<ViewProps>;
    Vector53628635?: PrimitiveOverrideProps<IconProps>;
    Vector53628636?: PrimitiveOverrideProps<IconProps>;
    Vector53628637?: PrimitiveOverrideProps<IconProps>;
    Group53628638?: PrimitiveOverrideProps<ViewProps>;
    Vector53628639?: PrimitiveOverrideProps<IconProps>;
    Vector53628640?: PrimitiveOverrideProps<IconProps>;
    Group53628641?: PrimitiveOverrideProps<ViewProps>;
    Vector53628642?: PrimitiveOverrideProps<IconProps>;
    Vector53628643?: PrimitiveOverrideProps<IconProps>;
    Vector53628644?: PrimitiveOverrideProps<IconProps>;
    Vector53628645?: PrimitiveOverrideProps<IconProps>;
    Vector53628646?: PrimitiveOverrideProps<IconProps>;
    Vector53628647?: PrimitiveOverrideProps<IconProps>;
    "Group 4"?: PrimitiveOverrideProps<ViewProps>;
    Vector53628649?: PrimitiveOverrideProps<IconProps>;
    Vector53628650?: PrimitiveOverrideProps<IconProps>;
    Settings?: PrimitiveOverrideProps<TextProps>;
    "Frame 280"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 274"?: PrimitiveOverrideProps<FlexProps>;
    "Headings with Lines53628654"?: PrimitiveOverrideProps<FlexProps>;
    Account?: PrimitiveOverrideProps<TextProps>;
    "Line 253628656"?: PrimitiveOverrideProps<IconProps>;
    "Frame 273"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 196"?: PrimitiveOverrideProps<FlexProps>;
    Username?: PrimitiveOverrideProps<TextProps>;
    "Your unique username displayed across Parazon."?: PrimitiveOverrideProps<TextProps>;
    "Frame 272"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 271"?: PrimitiveOverrideProps<FlexProps>;
    "@"?: PrimitiveOverrideProps<TextProps>;
    "Frame 173"?: PrimitiveOverrideProps<FlexProps>;
    "List Title"?: PrimitiveOverrideProps<TextProps>;
    "Update Button53628666"?: UpdateButtonProps;
    "Updated on June 10, 202353628667"?: PrimitiveOverrideProps<TextProps>;
    "Line 84"?: PrimitiveOverrideProps<IconProps>;
    "Delete Account Button"?: DeleteAccountButtonProps;
    "Frame 279"?: PrimitiveOverrideProps<FlexProps>;
    "Headings with Lines53628671"?: PrimitiveOverrideProps<FlexProps>;
    Payment?: PrimitiveOverrideProps<TextProps>;
    "Line 253628673"?: PrimitiveOverrideProps<IconProps>;
    "Frame 278"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 277"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 276"?: PrimitiveOverrideProps<FlexProps>;
    "Bank of America - jpeg 0"?: PrimitiveOverrideProps<IconProps>;
    "Frame 275"?: PrimitiveOverrideProps<FlexProps>;
    "Bank of America Visa Debit Card"?: PrimitiveOverrideProps<TextProps>;
    "Debit card ending in ... 0000"?: PrimitiveOverrideProps<TextProps>;
    "Bob B"?: PrimitiveOverrideProps<TextProps>;
    "United States"?: PrimitiveOverrideProps<TextProps>;
    "Updated on June 10, 202353628683"?: PrimitiveOverrideProps<TextProps>;
    "Update Button53628684"?: UpdateButtonProps;
    "Frame 298"?: PrimitiveOverrideProps<FlexProps>;
    "Headings with Lines53628686"?: PrimitiveOverrideProps<FlexProps>;
    Notifications?: PrimitiveOverrideProps<TextProps>;
    "Line 253628688"?: PrimitiveOverrideProps<IconProps>;
    "Frame 28753628689"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 286"?: PrimitiveOverrideProps<FlexProps>;
    Email?: PrimitiveOverrideProps<TextProps>;
    Notification?: PrimitiveOverrideProps<TextProps>;
    "Frame 285"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28453628694"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28253628695"?: PrimitiveOverrideProps<FlexProps>;
    "New Sales"?: PrimitiveOverrideProps<TextProps>;
    "Whenever you make a sale."?: PrimitiveOverrideProps<TextProps>;
    "Frame 28353628698"?: PrimitiveOverrideProps<FlexProps>;
    "Check Box button53628699"?: CheckBoxbuttonProps;
    "Check Box button53628700"?: CheckBoxbuttonProps;
    "Line 8553628701"?: PrimitiveOverrideProps<IconProps>;
    "Frame 28753628702"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28453628703"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28253628704"?: PrimitiveOverrideProps<FlexProps>;
    "New Favorites"?: PrimitiveOverrideProps<TextProps>;
    "Whenever someone favorites your prompts."?: PrimitiveOverrideProps<TextProps>;
    "Frame 28353628707"?: PrimitiveOverrideProps<FlexProps>;
    "Check Box button53628708"?: CheckBoxbuttonProps;
    "Check Box button53628709"?: CheckBoxbuttonProps;
    "Line 8553628710"?: PrimitiveOverrideProps<IconProps>;
    "Frame 288"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28453628712"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28253628713"?: PrimitiveOverrideProps<FlexProps>;
    "New Reviews"?: PrimitiveOverrideProps<TextProps>;
    "Whenever you receive a new review on your prompts or profile."?: PrimitiveOverrideProps<TextProps>;
    "Frame 28353628716"?: PrimitiveOverrideProps<FlexProps>;
    "Check Box button53628717"?: CheckBoxbuttonProps;
    "Check Box button53628718"?: CheckBoxbuttonProps;
    "Line 8553628719"?: PrimitiveOverrideProps<IconProps>;
    "Frame 294"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28453628721"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28253628722"?: PrimitiveOverrideProps<FlexProps>;
    "New Reply to Review"?: PrimitiveOverrideProps<TextProps>;
    "When someone replies to a review you leave."?: PrimitiveOverrideProps<TextProps>;
    "Frame 28353628725"?: PrimitiveOverrideProps<FlexProps>;
    "Check Box button53628726"?: CheckBoxbuttonProps;
    "Check Box button53628727"?: CheckBoxbuttonProps;
    "Line 8553628728"?: PrimitiveOverrideProps<IconProps>;
    "Frame 296"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28453628730"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28253628731"?: PrimitiveOverrideProps<FlexProps>;
    "Unusual Account Activities"?: PrimitiveOverrideProps<TextProps>;
    "When there is unusual account activities detected."?: PrimitiveOverrideProps<TextProps>;
    "Frame 28353628734"?: PrimitiveOverrideProps<FlexProps>;
    "Check Box button53628735"?: CheckBoxbuttonProps;
    "Check Box button53628736"?: CheckBoxbuttonProps;
    "Line 8553628737"?: PrimitiveOverrideProps<IconProps>;
    "Frame 293"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28453628739"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28253628740"?: PrimitiveOverrideProps<FlexProps>;
    "Monthly Summary"?: PrimitiveOverrideProps<TextProps>;
    "Summarize your performances in the last month."?: PrimitiveOverrideProps<TextProps>;
    "Frame 28353628743"?: PrimitiveOverrideProps<FlexProps>;
    "Check Box button53628744"?: CheckBoxbuttonProps;
    "Check Box button53628745"?: CheckBoxbuttonProps;
    "Line 8553628746"?: PrimitiveOverrideProps<IconProps>;
    "Frame 297"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28453628748"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 28253628749"?: PrimitiveOverrideProps<FlexProps>;
    "Answer to Your Question"?: PrimitiveOverrideProps<TextProps>;
    "When your question is solved."?: PrimitiveOverrideProps<TextProps>;
    "Frame 28353628752"?: PrimitiveOverrideProps<FlexProps>;
    "Check Box button53628753"?: CheckBoxbuttonProps;
    "Check Box button53628754"?: CheckBoxbuttonProps;
    "Line 8553628755"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type SettingsPageProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: SettingsPageOverridesProps | undefined | null;
}>;
export default function SettingsPage(props: SettingsPageProps): React.ReactElement;
